<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class QuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();
        $schedules = [
            [
                'id' => 1,
                'slug' => 'q1',
                'title' => 'ما إسم بطل رحلتنا',
                'type' => 'textInput',
                'options' => json_encode([
                    'placeholder' => 'اكتب الاسم هنا ...',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'slug' => 'q2',
                'title' => 'كم عمر بطل رحلتنا',
                'type' => 'choiceInput',
                'options' => json_encode([
                    'choices' => ['7-9', '9-11', '11-15'],
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'slug' => 'q3',
                'title' => 'ما أكثر شيء تتمنين تطويره لدى طفلك من خلال تعلم البرمجة',
                'type' => 'choiceInput',
                'options' => json_encode([
                    'choices' => ['التركيز', 'التفكير والإبداع', 'المهارات الإجتماعية', 'حل المشكلات', 'حب التعلم', 'إستغلال الطاقة بشكل إيجابي', 'العمل الجماعي', 'الثقة بالنفس'],
                    'required' => true,
                    'multiple' => true,
                    'hideFormText' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'slug' => 'q4',
                'title' => 'يشعر بطل رحلتنا بالملل سريعًا من الشرح التقليدي',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'slug' => 'q5',
                'title' => 'يفضل الحركة أو التفاعل أثناء التعلم',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'slug' => 'q6',
                'title' => 'يتحمس أكثر عندما يكون التعلم على شكل لعبة أو تحدي',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'slug' => 'q7',
                'title' => 'ينتقل بسرعة من نشاط إلى آخر',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'slug' => 'q8',
                'title' => 'يتفاعل بشكل أفضل مع الأنشطة العملية والتجارب',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'slug' => 'q9',
                'title' => 'يحب المنافسة والتحديات السريعة',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'slug' => 'q10',
                'title' => 'يتعلم بشكل أسرع عند مشاهدة الصور أو الفيديوهات',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'slug' => 'q11',
                'title' => 'يفضل تجربة الأشياء بنفسه بدل الاستماع للشرح فقط',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'slug' => 'q12',
                'title' => 'يتذكر ما يراه أكثر مما يسمعه',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'slug' => 'q13',
                'title' => 'يحب بناء أو تركيب الأشياء',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'slug' => 'q14',
                'title' => 'يستمتع باكتشاف حلول جديدة للمشكلات',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'slug' => 'q15',
                'title' => 'يطرح الكثير من الأسئلة بدافع الفضول',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'slug' => 'q16',
                'title' => 'يستمتع بالتعلم أو العمل مع الآخرين',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'slug' => 'q17',
                'title' => 'يفضل أحيانًا العمل بمفرده',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'slug' => 'q18',
                'title' => 'يتحفز أكثر عند التشجيع والمدح',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'slug' => 'q19',
                'title' => 'يشعر بالحماس عند وجود تحديات أو منافسة',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'slug' => 'q20',
                'title' => 'يتردد أو يتوتر في المجموعات الكبيرة',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'slug' => 'q21',
                'title' => 'يظهر تفاعلًا أفضل عندما يشعر بالراحة والحرية',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'slug' => 'q22',
                'title' => 'ينجذب إلى الألعاب أو الأنشطة التي تحتوي على تحديات وحلول',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'slug' => 'q23',
                'title' => 'يهتم بالتكنولوجيا أو الأجهزة أو الروبوتات',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'slug' => 'q24',
                'title' => 'يستمتع بالأفكار الإبداعية والتصميم والابتكار',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'slug' => 'q25',
                'title' => 'يسأل كثيرًا عن كيفية عمل الأشياء من حوله.',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'slug' => 'q26',
                'title' => 'يفضل الأنشطة التفاعلية أكثر من التعلم التقليدي',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'slug' => 'q27',
                'title' => 'يستمتع بالتجربة والاستكشاف أكثر من الحفظ والتلقين',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'slug' => 'q28',
                'title' => 'يحتاج إلى متابعة مستمرة للحفاظ على تركيزه',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'slug' => 'q29',
                'title' => 'يتعلم بشكل أفضل عند الحصول على اهتمام مباشر',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'slug' => 'q30',
                'title' => 'يتحفز أكثر عند التعلم مع مجموعة صغيرة',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'slug' => 'q31',
                'title' => 'يحتاج وقتًا إضافيًا لفهم التعليمات الجديدة',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'slug' => 'q32',
                'title' => 'يُظهر أداءً أفضل عندما يكون التعلم ممتعًا وغير تقليدي',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'slug' => 'q33',
                'title' => 'يتفاعل أكثر عندما يشعر بالحرية في التجربة والاستكشاف',
                'type' => 'opinionScale',
                'options' => json_encode([
                    'startAt' => 1,
                    'outOf' => 5,
                    'labelStart' => 'نادرا',
                    'labelEnd' => 'دائما',
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'slug' => 'q34',
                'title' => 'ما أكثر شيء يميز بطل رحلتنا؟',
                'type' => 'choiceInput',
                'options' => json_encode([
                    'choices' => ['فضولي ويحب الاكتشاف', 'مبدع وصاحب أفكار جديدة', 'يحب الحركة والتفاعل', 'يحب التحديات والمنافسة', 'يحب العمل مع الآخرين', 'مستقل ويحب التعلم بطريقته', 'سريع التعلم عند التجربة العملية', 'يحب التكنولوجيا والأفكار الحديثة'],
                    'required' => true,
                    'multiple' => true,
                    'hideFormText' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'slug' => 'q35',
                'title' => 'كيف تصفين بطل رحلتنا؟ شاركونا أكثر الصفات التي تميز شخصيته، وطريقته في التعلم أو التفاعل',
                'type' => 'textInput',
                'options' => json_encode([
                    'required' => true,
                    'placeholder' => 'اكتب الوصف هنا ...'
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'slug' => 'contact_phone',
                'title' => 'رقم الهاتف الخاص بالتواصل',
                'type' => 'textInput',
                'options' => json_encode([
                    'required' => true,
                    'placeholder' => '00201111111111'
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'slug' => 'contact_email',
                'title' => 'الإيميل الخاص للتواصل',
                'type' => 'emailInput',
                'options' => json_encode([
                    'required' => true,
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        Schema::disableForeignKeyConstraints();
        Question::truncate();
        Schema::enableForeignKeyConstraints();
        Question::insert($schedules);
    }
}
