---
deployment:
  tasks:
    - export DEPLOYPATH=/home/innoykbc/public_html/innovation-hub.app
    - cd $DEPLOYPATH && composer install
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan optimize:clear
    - cd $DEPLOYPATH && php artisan queue:restart
